language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home 캐싱기능 -gradle
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'

script: "mvn clean compile"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tkawnd111@gmail.com