# travis-ci.com 으로 이동

language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home 캐싱기능 -gradle
cache:
  directories:
    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'

script: "mvn clean compile"

before_deploy:
  - zip -r myblog-webservice
  - mkdir -p deploy
  - mv myblog-webservice.zip deploy/myblog-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: myblog-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tkawnd111@gmail.com