version: 0.0 #codedeploy 버전 / 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생한다.
os: linux
files:
  - source:  /  # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정한다.  '/' : 전체파일
    destination: /home/ec2-user/app/step3/zip/ # source에서 지정된 파일을 받을 위치. 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행한다.
    overwrite: yes # 기존에 있는 파일을 덮어쓸지 결정한다.

# CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정한다.
# ApplicationStar라는 단계에서 실행할 명령어를 지정한다.
# 스크립트 실행 60초 이상 수행되면 실패.한다.
hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료한다.
      timeout: 60
      runas: ec2-user
  ApplicationStar:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작한다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새로운 스프링 부트가 정상적으로 실행됬는지 확인한다.
      timeout: 60
      runas: ec2-user